### ISSUE TITLE
Firefox 63.0.3 (64 bit) don't work

### ISSUE THREAD

**Issue by darthmanfro** [jonashartmann/webcam-directive#73] opened 2018-11-22 10:48 UTC
It doesn't work, the example page does not work too ( https://jonas.hartmann.site/webcam-directive/#/ ).
There is no error only a warning:
navigator.mozGetUserMedia è stato sostituito da navigator.mediaDevices.getUserMedia

For me worked by 

changing this:
            videoElem.mozSrcObject = stream;
into:
            videoElem.srcObject = stream;

**Comment by robertmuth** [comment] 2018-11-25 19:57
I ran into the same issue
BTW: the englisjh version of the warning is:
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

**Comment by dalelane** [comment] 2018-11-26 20:52
I think there is already a fix for this : https://github.com/jonashartmann/webcam-directive/pull/67 

The problem is that this hasn't been published in a build. But if you grab the source for yourself from github, I _think_ you might be okay.

**Comment by jonashartmann** [comment] 2019-01-19 16:09
I've updated it to 3.2.0 to fix those issues. See #70 
I still need to update the demo page #69

**Comment by jonashartmann** [comment] 2019-01-19 17:18
Demo page was updated.

**Closed by jonashartmann** 2019-01-19 17:18 UTC
